name: CI/CD example

on:
  workflow-dispatch

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "eu-central-1"
  AWS_S3_PATH: s3://playwire-mobile-test/c-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build application
        run: gcc main.c -o hello-world

      - uses: actions/upload-artifact@v3.0.0
        with:
          path: hello-world


  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: ['dev', 'prod']


    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::519140963702:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Download all workflow run artifact
        uses: actions/download-artifact@v4

      - name: Publish app files
        run: |
          aws s3 cp artifact/hello-world ${{ env.AWS_S3_PATH }}/${{ matrix.environment }}/hello-world



