name: S3 Continuous Deployment to dev

on:
  push:
    branches: [ 'master', 'dev' ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "eu-central-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build application
        run: gcc main.c -o hello-world

      - uses: actions/upload-artifact@v3.0.0
        with:
          path: hello-world


  deploy-dev:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: build
    runs-on: ubuntu-latest
    environment: dev

    env:
      AWS_S3_PATH: s3://playwire-mobile-test/c-app

    steps:

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::519140963702:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}}

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Publish on dev
        run: |
          aws s3 cp hello-world ${{ env.AWS_S3_PATH }}


  # deploy-prod:
  #   if: ${{ github.ref == 'refs/heads/master' }}
  #   needs: build
  #   runs-on: ubuntu-latest
  #   environment: prod

  #   steps:
  #     - name: Download all workflow run artifacts
  #       uses: actions/download-artifact@v3

  #     - name: Publish on prod
  #       run: |
  #         aws s3 cp hello-world ${{ env.AWS_S3_PATH }}






    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::111111111111:role/my-github-actions-role-test
        aws-region: us-east-1

    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync . s3://my-s3-test-website-bucket

    - name: Configure AWS credentials from Production account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::222222222222:role/my-github-actions-role-prod
        aws-region: us-west-2

    - name: Copy files to the production website with the AWS CLI
      run: |
        aws s3 sync . s3://my-s3-prod-website-bucket