name: S3 Continuous Deployment to dev

on:
  push:
    branches: [ 'master', 'dev' ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "eu-central-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build application
        run: gcc main.c -o hello-world

      - uses: actions/upload-artifact@v3.0.0
        with:
          path: hello-world


  deploy-dev:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: build
    runs-on: ubuntu-latest
    environment: dev

    env:
      AWS_S3_PATH: s3://playwire-mobile-test/c-app

    steps:

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::519140963702:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Publish on dev
        run: |
          aws s3 cp hello-world ${{ env.AWS_S3_PATH }}


  # deploy-prod:
  #   if: ${{ github.ref == 'refs/heads/master' }}
  #   needs: build
  #   runs-on: ubuntu-latest
  #   environment: prod

  #   steps:
  #     - name: Download all workflow run artifacts
  #       uses: actions/download-artifact@v3

  #     - name: Publish on prod
  #       run: |
  #         aws s3 cp hello-world ${{ env.AWS_S3_PATH }}




