name: Local Testing

on:
  push

jobs:
  build:
    name: Local Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build application
        run: gcc main.c -o hello-world

      - uses: actions/upload-artifact@v3.0.0
        with:
          path: hello-world

