name: Local Testing

on:
  push

jobs:
  test:
    name: Local Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Hello World
        run: echo 'Hello World'