name: Local Testing

on:
  push

jobs:
  build:
    name: Local Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build application
        run: gcc main.c -o hello-world

      - run: git clone git@github.com:wandervik/github-actions-tut.git

      - run: echo 'test successful'

