name: Loop

on:
  push

jobs:
  loop:
    name: Loop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: date > test.txt

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Changes