name: Matrix

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'url'
        required: true
        default: 'https://example.com'
      TestFilter:
        description: 'Test description. Filter by tags: Category=<specflowTag1> | Category=<specflowRag2>.'
        required: false
        default: 'Category=Ready'

jobs:
   example_matrix:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 0
      matrix:
        TestFilter: [Category=Chrome, Category=Firefox, Category=Safari,  "${{ github.event.inputs.TestFilter }}"]
    steps:
#       - uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.version }}
      - uses: actions/checkout@v2

#       - run: node --version
      - name: Show inputs
        run: |
          echo "url: ${{ github.event.inputs.URL }}"
          echo "test filter: ${{ matrix.TestFilter }}"
