name: Matrix

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'url'
        required: true
        default: 'https://example.com'
      Category:
        description: 'Test description. Filter by tags: Category=<specflowTag1> | Category=<specflowRag2>.'
        required: false
        default: 'Category=Ready | Category=LMS9'
      Browser:
        description: 'Test description. Filter by tags: Category=<specflowTag1> | Category=<specflowRag2>.'
        required: false
        default: 'Category=Browser:Chrome | Category=Browser:Safary | Category=Browser:Edge'

jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github
    outputs:
      matrix-browser: ${{ steps.convert-json.outputs.matrix-browser }}
      matrix-category: ${{ steps.convert-json-cat.outputs.matrix-category }}

    steps:
      - uses: actions/checkout@v4
      - name: Convert Browser to JSON
        id: convert-json
        run: |
          echo "::set-output name=matrix-browser::$(python ./jsonify.py '${{ github.event.inputs.Browser }}')"
          python ./jsonify.py '${{ github.event.inputs.Browser }}'

      - name: Convert to JSON
        id: convert-json-cat
        run: |
          echo "::set-output name=matrix-category::$(python ./jsonify.py '${{ github.event.inputs.Category }}')"
          python ./jsonify.py '${{ github.event.inputs.Category }}'

  job1:
    strategy:
      matrix:
        Category: ${{ fromJSON(needs.setup.outputs.matrix-category) }}
    needs: [setup]
    if: contains(github.event.inputs.Browser, 'Category=Browser:Edge')
    runs-on: ubuntu-latest  #windows-self-hosted

    steps:
      - run: echo "My runner is windows"

      - name: Show inputs
        run: |
          echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
          echo "TEST FILTER IS Category=Browser:Edge | ${{ matrix.Category}}"

  job2:
    strategy:
      matrix:
        TestFilter: ${{ fromJSON(needs.setup.outputs.matrix-browser) }}
        Category: ${{ fromJSON(needs.setup.outputs.matrix-category) }}
        exclude:
          - TestFilter: "Category=Browser:Edge"

    needs: [setup]
    if: github.event.inputs.Browser != 'Category=Browser:Edge'
    runs-on: ubuntu-latest #ubuntu-self-hostef

    steps:

      - name: Show inputs
        run: |
          echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
          echo "TEST FILTER IS ${{ matrix.TestFilter }} | ${{ matrix.Category }}"
