name: Matrix

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'url'
        required: true
        default: 'https://example.com'
      Category:
        description: 'Test description. Filter by tags: Category=<specflowTag1> | Category=<specflowRag2>.'
        required: false
        default: 'Category=Ready | Category=LMS9'
      Browser:
        description: 'Test description. Filter by tags: Category=<specflowTag1> | Category=<specflowRag2>.'
        required: false
        default: 'Category=Browser:Chrome | Category=Browser:Safary | Category=Browser:Edge'
env:
  Category=Browser:Edge : windows
  Category=Browser:Chrome : ubuntu-latest
  Category=Browser:Safari : ubuntu-latest
  Category=Browser:Firefox : ubuntu-latest

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      runner1: ${{ steps.step1.outputs.runner1 }}
      runner2: ${{ steps.step1.outputs.runner2 }}
      TestFilter1: ${{ steps.step1.outputs.TestFilter1 }}
      TestFilter2: ${{ steps.step1.outputs.TestFilter2 }}
      matrix-browser: ${{ steps.convert-json.outputs.matrix-browser }}
      matrix-category: ${{ steps.convert-json-cat.outputs.matrix-category }}

    steps:
      - uses: actions/checkout@v2
      - name: Convert Browser to JSON
        id: convert-json
        run: |
          echo "::set-output name=matrix-browser::$(python ./jsonify.py '${{ github.event.inputs.Browser }}')"
          python ./jsonify.py '${{ github.event.inputs.Browser }}'

      - name: Convert to JSON
        id: convert-json-cat
        run: |
          echo "::set-output name=matrix-category::$(python ./jsonify.py '${{ github.event.inputs.Browser }}')"
          python ./jsonify.py '${{ github.event.inputs.Category }}'

      # - name: Check browser
      #   id: step1
      #   run: |
      #     if [[ "${{ github.event.inputs.TestFilter }}" == "Browser=Edge" ]]; then
      #       echo "::set-output name=runner1::windows"
      #       echo "Edge Only"
      #     elif [[ "${{ github.event.inputs.TestFilter }}" != *Edge* ]]; then
      #       echo "::set-output name=runner2::ubuntu"
      #       echo "Edge contains"
      #     else
      #       echo "::set-output name=runner2::ubuntu"
      #       echo "NO EDGE"
      #     fi



  job1:
    strategy:
      matrix:
        Category: ${{ fromJSON(needs.setup.outputs.matrix-category) }}
    needs: [setup]
    # if: needs.setup.outputs.runner1 == 'windows'
    if: contains (github.event.inputs.Browser, "Category=Browser:Edge")
    # runs-on: ${{ needs.setup.outputs.runner }}
    runs-on: ubuntu-latest

    steps:
      - run: echo "My runner is windows"

      - name: Show inputs
        run: |
          echo "test filter is Browser=Edge | ${{ matrix.Category}}"

  job2:
    strategy:
      matrix:
        TestFilter: ${{ fromJSON(needs.setup.outputs.matrix-browser) }}
        Category: ${{ fromJSON(needs.setup.outputs.matrix-category) }}
        exclude:
          - TestFilter: "Category=Browser:Edge"

    needs: [setup]
    if: github.event.inputs.Browser != "Category=Browser:Edge"
    # runs-on: ${{ needs.setup.outputs.runner }}
    runs-on: ubuntu-latest

    steps:
      # - run: echo "My runner is ${{ needs.setup.outputs.runner }}"

      - name: Show inputs
        run: |
          echo "test filter: ${{ matrix.TestFilter }} | ${{ matrix.Category }}"
# jobs:
#    edge_example_matrix:

#     runs-on: ubuntu-latest
#     if: TestFilter='Category=Ready'

#     env:
#         TestFilter: Category=Edge
#     steps:
#       # - uses: actions/setup-node@v3
#       #   with:
#       #     node-version: ${{ matrix.version }}
#       - uses: actions/checkout@v2

# #       - run: node --version
#       - name: Show inputs
#         run: |
#           echo "url: ${{ github.event.inputs.URL }}"
#           echo "test filter: ${{ env.TestFilter }}"
