name: Matrix

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'url'
        required: true
        default: 'https://example.com'
      TestFilter:
        description: 'Test description. Filter by tags: Category=<specflowTag1> | Category=<specflowRag2>.'
        required: false
        default: 'Category=Ready'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.step1.outputs.runner }}
    steps:
      - name: Check branch
        id: step1
        run: |
          if [ ${{ github.event.inputs.TestFilter }} == 'TEST' ]; then
            echo "::set-output name=runner::TEST"
          else
            echo "::set-output name=runner::macos-latest"
          fi

  job1:
    needs: [setup]
    if: needs.setup.outputs.runner == 'TEST'
    # runs-on: ${{ needs.setup.outputs.runner }}
    runs-on: ubuntu-latest

    env:
      TestFilter: 'Category=Edge'
    steps:
      - run: echo "My runner is ${{ needs.setup.outputs.runner }}"

      - name: Show inputs
        run: |
          echo "url: ${{ github.event.inputs.URL }}"
          echo "test filter: ${{ env.TestFilter }}"

  job2:
    strategy:
      matrix:
        TestFilter: [Category=Edge, Category=Chrome]

    needs: [setup]
    if: needs.setup.outputs.runner != 'TEST'
    # runs-on: ${{ needs.setup.outputs.runner }}
    runs-on: ubuntu-latest

    steps:
      - run: echo "My runner is ${{ needs.setup.outputs.runner }}"

      - name: Show inputs
        run: |
          echo "url: ${{ github.event.inputs.URL }}"
          echo "test filter: ${{ env.TestFilter }}"

# jobs:
#    edge_example_matrix:

#     runs-on: ubuntu-latest
#     if: TestFilter='Category=Ready'

#     env:
#         TestFilter: Category=Edge
#     steps:
#       # - uses: actions/setup-node@v3
#       #   with:
#       #     node-version: ${{ matrix.version }}
#       - uses: actions/checkout@v2

# #       - run: node --version
#       - name: Show inputs
#         run: |
#           echo "url: ${{ github.event.inputs.URL }}"
#           echo "test filter: ${{ env.TestFilter }}"