name: Matrix

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'url'
        required: true
        default: 'https://example.com'
      TestFilter:
        description: 'Test description. Filter by tags: Category=<specflowTag1> | Category=<specflowRag2>.'
        required: false
        default: 'Browser=Chrome, Browser=Safary, Browser=Edge'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      runner1: ${{ steps.step1.outputs.runner1 }}
      runner2: ${{ steps.step1.outputs.runner2 }}
      TestFilter1: ${{ steps.step1.outputs.TestFilter1 }}
      TestFilter2: ${{ steps.step1.outputs.TestFilter2 }}
    steps:
      - name: Check browser
        id: step1
        run: |
          if [ "${{ github.event.inputs.TestFilter }}" == "Browser=Edge" ]; then
            echo "::set-output name=runner1::windows"
            echo "::set-output name=TestFilter1::Browser=Edge"
            echo "Edge Only"
          elif [ "${{ github.event.inputs.TestFilter }}" == *"Edge"* ]; then
            echo "::set-output name=runner2::ubuntu"
            echo "::set-output name=runner1::windows"
            echo "::set-output name=TestFilter1::Browser=Edge"
            TESTFILTER=${{ github.event.inputs.TestFilter }}
            TESTFILTER=${TESTFILTER/Browser=Edge, /}
            TESTFILTER=${TESTFILTER/, Browser=Edge/}
            echo "::set-output name=TestFilter2::$TESTFILTER"
            echo "Edge contains"
          else
            echo "::set-output name=runner2::ubuntu"
            echo "::set-output name=TestFilter2::${{ github.event.inputs.TestFilter }}"
            echo "NO EDGE"
          fi



  job1:
    needs: [setup]
    if: needs.setup.outputs.runner1 == 'windows'
    # runs-on: ${{ needs.setup.outputs.runner }}
    runs-on: ubuntu-latest

    steps:
      - run: echo "My runner is ${{ needs.setup.outputs.runner1 }}"

      - name: Show inputs
        run: |
          echo "test filter: ${{ needs.setup.outputs.TestFilter1 }}"

  job2:
    strategy:
      matrix:
        TestFilter: ${{ needs.setup.outputs.TestFilter2 }}

    needs: [setup]
    if: needs.setup.outputs.runner2 == 'ubuntu'
    # runs-on: ${{ needs.setup.outputs.runner }}
    runs-on: ubuntu-latest

    steps:
      - run: echo "My runner is ${{ needs.setup.outputs.runner }}"

      - name: Show inputs
        run: |
          echo "test filter: ${{ needs.setup.outputs.TestFilter2 }}"
# jobs:
#    edge_example_matrix:

#     runs-on: ubuntu-latest
#     if: TestFilter='Category=Ready'

#     env:
#         TestFilter: Category=Edge
#     steps:
#       # - uses: actions/setup-node@v3
#       #   with:
#       #     node-version: ${{ matrix.version }}
#       - uses: actions/checkout@v2

# #       - run: node --version
#       - name: Show inputs
#         run: |
#           echo "url: ${{ github.event.inputs.URL }}"
#           echo "test filter: ${{ env.TestFilter }}"