name: On Release Testing

on:
  release:
    types: [created]
jobs:
  outputs:
    name: Steps Outputs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test 1
        run: echo "Success"
