name: On Release Testing

on:
  release:
    types: [created]
jobs:
  outputs:
    name: Steps Outputs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Master
        if: github.ref_name == 'main'
        run: echo ${{github.ref_name}}
        
      - name: Release
        if: startsWith(github.ref_name, 'v')
        run: echo "Condition success"
        
        
