name: Local Testing

on:
  push

jobs:
  outputs:
    name: Steps Outputs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get new version
        id: new_version
        uses: notiz-dev/github-action-json-property@release
        with:
            path: 'package.json'
            prop_path: 'version'

      - name: Deploy
        run: |
          echo 's3://sample-path/${{steps.new_version.outputs.prop}}'