name: Test app

on:
  workflow_dispatch

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build application
        run: gcc main.c -o hello-world

      - uses: actions/upload-artifact@v3.0.0
        with:
          path: hello-world


